name: Bug report
description: Something isn't working as expected
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect instead?
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - backend
        - frontend
        - infra/CI
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
    validations:
      required: false
